WHSIC/WHSIC/Controllers/ServiceesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WHSIC.Data;
using WHSIC.Model;
using WHSIC.BusinessLogic;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.IO;

namespace WHSIC.Controllers
{
    public class ServiceesController : Controller
    {
        BaseFont f_cb = BaseFont.CreateFont("c:\\windows\\fonts\\calibrib.ttf", BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
        BaseFont f_cn = BaseFont.CreateFont("c:\\windows\\fonts\\calibri.ttf", BaseFont.CP1252, BaseFont.NOT_EMBEDDED);

        InternetTime it = new InternetTime();
        ServiceeBusiness sb = new ServiceeBusiness();
        ServiceTypeBusiness st = new ServiceTypeBusiness();

        public List<ServiceTypeViewModel>sType()
        {
            List<ServiceTypeViewModel> typeList = (from s in st.GetAllServiceType() where s.dismiss == true select s).ToList();
            return typeList;
        }

        [Authorize(Roles = "Treasure")]
        public ActionResult Index()
        {
            return View(sb.GetAllService());
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.feed = null;
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServiceeViewModel servicee)
        {
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            if (ModelState.IsValid)
            {
                string email = User.Identity.Name;
                if (servicee.Quantity < 1)
                {
                    ViewBag.feed = "Invalid quantity, enter correct quantity..!";
                }
                else
                {
                    DateTime newdate = Convert.ToDateTime(servicee.Date.ToShortDateString());
                    DateTime netdate = Convert.ToDateTime(it.GetNistTime().ToShortDateString());

                    if (newdate < netdate)
                    {
                        ViewBag.feed = "Date entered has passed, enter correct date..!";
                    }
                    else
                    {
                        servicee.email = email;
                        servicee.Status = false;
                        sb.AddService(servicee);
                        ModelState.Clear();
                        ViewBag.feed = "Your service is successfully saved, Thank you for your service..!";
                        return RedirectToAction("GetAllMyDonations","ViewMyDonations" );
                    }
                }
            }
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");

            return View();
        }
        [Authorize(Roles = "Treasure")]
        public ActionResult Edit(int? id)
        {
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            ViewBag.feed = null;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceeViewModel servicee = sb.GetbyID(Convert.ToInt32(id));
            if (servicee == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = servicee.email;
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            return View(servicee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ServiceeViewModel servicee,FormCollection form)
        {
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            if (ModelState.IsValid)
            {
                servicee.email = form["txtname"];
                if(servicee.Status==true)
                {
                    sb.UpdateService(servicee);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.feed = "Service is not updated, change service status..!!";
                }
               
            }
            ViewBag.name = form["txtname"];
            ViewBag.m = new SelectList(sType(), "TypeID", "Description");
            return View(servicee);
        }


        public FileStreamResult PrintService(int id)
        {

            ServiceeViewModel serv = sb.GetbyID(id);
            ServiceTypeViewModel type = st.GetbyID(serv.TypeID);
            

            string imagepath = Server.MapPath("~/Images");


            Document doc = new Document(PageSize.A4, 0, 0, 0, 0);
            var ms = new MemoryStream();

            PdfWriter writer = PdfWriter.GetInstance(doc, ms);

            doc.Open();
            PdfContentByte cb = writer.DirectContent;
            cb.AddTemplate(PdfFooterExt(cb), 30, 1);

            Font address_font = FontFactory.GetFont(FontFactory.TIMES_ROMAN, 9, Font.ITALIC, BaseColor.BLACK);
            //Text Settings
            string text = "Payment Details";
            Font georgia = FontFactory.GetFont("georgia", 24f);
            georgia.Color = BaseColor.BLACK;
            Chunk beginning = new Chunk(text, georgia);




            Font font_heading_3 = FontFactory.GetFont(FontFactory.TIMES_ROMAN, 16, Font.BOLD, BaseColor.MAGENTA);
            Font font_body = FontFactory.GetFont(FontFactory.TIMES_ROMAN, 13, Font.BOLDITALIC, BaseColor.BLUE);
            Font headingaddress = FontFactory.GetFont(FontFactory.TIMES_ROMAN, 13, Font.BOLD, BaseColor.BLACK);




            // Create the heading paragraph with the headig font
            Paragraph heading;
            heading = new Paragraph("WELCOME HOLY SPIRIT INTERNATIONAL CHURCH", font_heading_3);

            Paragraph thankf;
            thankf = new Paragraph("--------------Thank you for your Donation have a nice day and God bless you---------------", font_body);

            Paragraph address;
            address = new Paragraph("Head Office", headingaddress);
            Paragraph StreetNo;
            StreetNo = new Paragraph("E1210 UMBALANE ROAD", address_font);
            Paragraph location;
            location = new Paragraph("Ntuzuma", address_font);

            Paragraph city;
            city = new Paragraph("Durban", address_font);

            Paragraph code;
            code = new Paragraph("4360", address_font);

            PdfPTable table = new PdfPTable(2);
            table.DefaultCell.Border = Rectangle.NO_BORDER;


            PdfPCell cell = new PdfPCell(new Phrase(beginning));

            PdfPTable table1 = new PdfPTable(1);
            table1.DefaultCell.Border = Rectangle.NO_BORDER;

            PdfPCell cell2 = new PdfPCell(heading);
            PdfPCell cellt = new PdfPCell(thankf);

            cell2.Colspan = 1;
            cell2.HorizontalAlignment = 1;

            //PdfPCell cell1 = new PdfPCell(new Phrase(Ending));
            cell.Colspan = 2;
            cell.HorizontalAlignment = 1; //0=Left, 1=Centre, 2=Right



            PdfPTable table2 = new PdfPTable(2);
            table2.DefaultCell.Border = Rectangle.NO_BORDER;


            PdfPTable tbthank = new PdfPTable(1);
            tbthank.DefaultCell.Border = Rectangle.NO_BORDER;

            Font slogan_font = FontFactory.GetFont(FontFactory.TIMES_ROMAN, 13, Font.ITALIC, BaseColor.BLUE);

            Paragraph slogan;
            slogan = new Paragraph("                 People with the mandate and influence of the holy spirit", slogan_font);


            tbthank.AddCell(thankf);
            table1.AddCell(cell2);
            table1.AddCell(slogan);
            table1.AddCell(address);
            table1.AddCell(StreetNo);
            table1.AddCell(location);
            table1.AddCell(city);
            table1.AddCell(code);
            table.AddCell(cell);
            //table.AddCell(cell1);
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Donated by");
            table.AddCell(serv.email);
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Donation Type");
            table.AddCell("Service");
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Type of Service");
            table.AddCell(type.Description);
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Service Name");
            table.AddCell(serv.Service_name);
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Quantity");
            table.AddCell(serv.Quantity.ToString());
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Date");
            table.AddCell(ReportDate(serv.Date));
            table.AddCell("              ");
            table.AddCell("              ");

            table.AddCell("Time");
            table.AddCell(it.GetNistTime().ToShortTimeString());
            table.AddCell("              ");
            table.AddCell("              ");
            



            //Add Image
            iTextSharp.text.Image jpg = iTextSharp.text.Image.GetInstance(imagepath + "/SCAN0008.JPG");
            jpg.ScaleToFit(300f, 150f);
            jpg.Alignment = Element.ALIGN_CENTER;
            jpg.Border = Rectangle.BOX;
            jpg.BorderColor = BaseColor.LIGHT_GRAY;
            jpg.BorderColorTop = BaseColor.WHITE;
            jpg.BorderWidth = 3f;

            Phrase phrase = new Phrase(Environment.NewLine);
            Phrase phrase1 = new Phrase(Environment.NewLine);
            Phrase phrase2 = new Phrase(Environment.NewLine);


            //doc.Add();
            doc.Add(phrase1);
            doc.Add(table1);
            doc.Add(jpg);

WHSIC/WHSIC/Views/Servicees/Create.cshtml
@model WHSIC.Model.ServiceeViewModel
@{
    ViewBag.Title = "Create";
}
<br />
<h2 class="text-center" style="padding-top:20px;">Provide service</h2>
<div style="padding:10px 30px 10px 70px">
    <div class="alert alert-info alert-dismissible text-center" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Greeting!</strong> <p>
            If the type of service you want to donate is not in the list of our service type,<br />
            it may happen that the church is not in need of that particular service or please feel free to contact us.
            Just go straigth to contact us page...
        </p>
    </div>
</div>

<div style="padding-left:30%">
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", (SelectList)ViewBag.m, "---Select Service Type--", new { @style = "width:279px;height:36px;" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Service_name, new { htmlAttributes = new { @class = "form-control",placeholder="Enter service name here" } })
                @Html.ValidationMessageFor(model => model.Service_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter the quantity here" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("I will deliver it on", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="padding-left:10%">
                <input type="submit" value="Donate" class="btn btn-primary" />
            </div>
        </div>

        <div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back", "ChooseDonation","ExternalDonor", null, new { @class = "fa fa-arrow-circle-o-left", @style = "Font-size:30px;" })
                </div>
            </div>
        </div>
    </div>
}
@if(ViewBag.feed!=null)
{
    <script>
        alert("@ViewBag.feed")
    </script>
}

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}




@*<div class="alert alert-success" role="alert">
    <a href="#" class="alert-link">...</a>
</div>
<div class="alert alert-info" role="alert">
    <a href="#" class="alert-link">...</a>
</div>
<div class="alert alert-warning" role="alert">
    <a href="#" class="alert-link">...</a>
</div>
<div class="alert alert-danger" role="alert">
    <a href="#" class="alert-link">...</a>
</div>*@

WHSIC/WHSIC/Views/Servicees/Edit.cshtml
@model WHSIC.Model.ServiceeViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2 class="text-center">Edit</h2>
<div class="well" style="padding-left:20%">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Servicee</h4>
            <hr />
            <div>
                <input type="text" name="txtname" value="@ViewBag.name" hidden />
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Service_id)
            @Html.HiddenFor(m=>m.TypeID)

            <div class="form-group">
                @Html.Label("Service Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Service_name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.Service_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Received?", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Received on", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

           

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    @if(ViewBag.feed!=null)
    {
        <script>
            alert("@ViewBag.feed")
        </script>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WHSIC/WHSIC/Views/Servicees/Index.cshtml
@model IEnumerable<WHSIC.Model.ServiceeViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<h2 class="text-center">List of Services</h2>
<div class="well">
    <table class="table table-bordered table-hover table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Service_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayName("Received?")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Service_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.ActionLink("Update status", "Edit", new { id = item.Service_id }) 

                </td>
                <td>
                    @if(item.Status==true)
                    {
                        <div>
                            <button style="font-size:11px;color:darkblue" class="fa fa-print" onclick="window.open('@Url.Action("PrintService", "Servicees", new { id = item.Service_id })')">Print</button>
                        </div>
                    }
               
                </td>
                
            </tr>
        }

    </table>
</div>