WHSIC/WHSIC/Controllers/Expense_PaidController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Cache;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using WHSIC.BusinessLogic;
using WHSIC.Data;
using WHSIC.Model;

namespace WHSIC.Controllers
{
    public class Expense_PaidController : Controller
    {
        Expense_PaidBusiness eb = new Expense_PaidBusiness();
        ExpenseBusiness exb = new ExpenseBusiness();
        PaidExpenseReceiptBusiness _perb = new PaidExpenseReceiptBusiness();
        ApplicationDbContext db = new ApplicationDbContext();
        private NotificationBusiness nb = new NotificationBusiness();
        private EmployeeBusiness _eb = new EmployeeBusiness();
        private string Report = "";

        public FileStreamResult Showfile(int? id)
        {
            Stream output = new MemoryStream(getContract((int)id).Receipt);
            return new FileStreamResult(output, "application/pdf");
        }
        public PaidExpenseReceiptViewModel getContract(int id)
        {
            return _perb.GetbyID(id);
        }
        private byte[] readFileContents(HttpPostedFileBase file)
        {
            Stream fileStream = file.InputStream;
            var mStreamer = new MemoryStream();
            mStreamer.SetLength(fileStream.Length);
            fileStream.Read(mStreamer.GetBuffer(), 0, (int)fileStream.Length);
            mStreamer.Seek(0, SeekOrigin.Begin);
            byte[] fileBytes = mStreamer.GetBuffer();
            return fileBytes;
        }

        public JsonResult GetEmployees(string term)
        {
            var employee = eb.GetAllExpenses_Paid().Where(x => x.ExpenseDesc.ToUpper().StartsWith(term.ToUpper())).Select(y => y.ExpenseDesc).ToList();
            return Json(employee, JsonRequestBehavior.AllowGet);
        }


        [Authorize(Roles = "Treasure")]
        public ActionResult Index(int?page)
        {
            const int pageSize = 5;
            int pageNo = (page ?? 1);

            var list = eb.GetAllExpenses_Paid().OrderByDescending(x=>x.paid_exp_id);

            return View(list.ToPagedList(pageNo, pageSize));
        }

        [HttpPost]
        public ActionResult Index(string searchTerm, int? page)
        {
            const int pageSize = 5;
            int pageNo = (page ?? 1);

            List<Expense_PaidViewModel> Employee;

            if (string.IsNullOrEmpty(searchTerm))
            {
                Employee = eb.GetAllExpenses_Paid();
            }
            else
            {
                Employee = eb.GetAllExpenses_Paid().Where(x => x.ExpenseDesc.StartsWith(searchTerm)).ToList();
            }
            var list = Employee;
            return View(list.ToPagedList(pageNo, pageSize));
        }

        public List<ExpenseViewModel>ExpenseName()
        {
            List<ExpenseViewModel> myList = (from e in exb.GetAllExpenses() where e.recurring == false select e).ToList();
            return myList;
        }
        public void SubtractIncome(decimal amt)
        {
            decimal val = 0;

            foreach (var CO in db.Incomes.ToList())
            {
                val = CO.TotIncome;
                val = val - amt;
                CO.TotIncome = val;
                db.SaveChanges();
                break;
            }
        }
        [Authorize(Roles = "Treasure")]
        public ActionResult Create()
        {
            ViewBag.m = new SelectList(ExpenseName(), "exp_id", "desc");

            return View();
        }
        [HttpPost]
        public ActionResult Create(Expense_PaidViewModel model, HttpPostedFileBase file)
        {
            EmployeeViewModel emp = _eb.GetAllEmployee().Find(x => x.Email == User.Identity.Name);

            ViewBag.m = new SelectList(ExpenseName(), "exp_id", "desc");
            try
            {
                ExpenseViewModel exp = exb.GetAllExpenses().Find(x => x.exp_id == model.exp_id);
                    if (model.amount_paid <= exp.amount)
                    {
                        model.Receipt = readFileContents(file);
                        eb.AddExpense_Paid(model);
                        SubtractIncome(model.amount_paid);
                        Report = emp.FirstName + " " + emp.LastName + " has added the payment record for " + exp.desc + " expense";

                        AddNotification(Report);
                        return RedirectToAction("Index");
                    }
                    ViewBag.feed = "Amount paid cannot exceeds the expense amount...!!";
            }
            catch (Exception d)
            {
                ViewBag.feed = d.Message;
            }
            ViewBag.m = new SelectList(ExpenseName(), "exp_id", "desc");
            return View();
        }
        [Authorize(Roles = "Treasure, Admin")]
        public ActionResult Details(int id)
        {
            Expense_PaidViewModel evm = eb.GetbyID(Convert.ToInt32(id));

            return View(evm);
        }
        [Authorize(Roles = "Treasure")]
        public ActionResult Edit(int? id)
        {
            ViewBag.m = new SelectList(exb.GetAllExpenses(), "exp_id", "desc");
            Expense_PaidViewModel evm = eb.GetbyID(Convert.ToInt32(id));
            return View(evm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Expense_PaidViewModel model, HttpPostedFileBase File)
        {
            EmployeeViewModel emp = _eb.GetAllEmployee().Find(x => x.Email == User.Identity.Name);
            ViewBag.m = new SelectList(exb.GetAllExpenses(), "exp_id", "desc");
            try
            {
                Expense_PaidViewModel e = eb.GetAllExpenses_Paid().Find(x => x.paid_exp_id == model.paid_exp_id);

                ExpenseViewModel exp = exb.GetAllExpenses().Find(x => x.exp_id == e.exp_id);

                decimal totpayed = model.amount_paid + e.amount_paid;

                    if (totpayed <= exp.amount)
                    {
                        model.Receipt = readFileContents(File); 

                        model.amount_paid = model.amount_paid + e.amount_paid;

                        eb.UpdateExpense_Paid(model);
                        SubtractIncome(model.amount_paid);

                        Report = emp.FirstName + " " + emp.LastName + " has updated the payment record for " + model.ExpenseDesc + " expense";

                        AddNotification(Report);

                        return RedirectToAction("Index");
                    }
                    ViewBag.feed = "Amount paid cannot exceeds the expense amount...!! ";
               
            }
            catch (Exception f)
            {

            }
            ViewBag.m = new SelectList(exb.GetAllExpenses(), "exp_id", "desc");
            return View(model);
        }


        public void AddNotification(string reportp)
        {
            NotificationViewModel not = new NotificationViewModel
            {
                Text = reportp,
                DateTime = GetNistTime()
            };
            nb.AddNotification(not);
        }

        [Authorize(Roles = "Treasure")]
        public ActionResult Delete(int? id)
        {
            Expense_PaidViewModel evm = eb.GetbyID(Convert.ToInt32(id));
            return View(evm);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            EmployeeViewModel emp = _eb.GetAllEmployee().Find(x => x.Email == User.Identity.Name);
            try
            {
                Expense_PaidViewModel ep = eb.GetbyID(id);
                eb.DeleteExpense_Paid(id);

                Report = emp.FirstName + " " + emp.LastName + " has deleted the payment record for "+ ep.ExpenseDesc+ " expense";

                AddNotification(Report);
                return RedirectToAction("Index");
            }
            catch (Exception b)
            {

            }
            return View();
        }

        public ActionResult ExpenseReceipt(int id)
        {
            var Reciepts = (from r in _perb.GetAllExpenses_PaidReceipt() where r.paid_exp_id == id select r).ToList();
            ViewBag.count = Reciepts.Count;
            return View(Reciepts);
        }

        public ActionResult DeleteReceipt(int? id)
        {
            EmployeeViewModel emp = _eb.GetAllEmployee().Find(x => x.Email == User.Identity.Name);
           
            PaidExpenseReceiptViewModel peb = _perb.GetbyID(Convert.ToInt32(id));
            Expense_PaidViewModel ep = eb.GetAllExpenses_Paid().Find(x=>x.paid_exp_id==peb.paid_exp_id);
            ExpenseViewModel ee = exb.GetAllExpenses().Find(x => x.exp_id == ep.exp_id);
            try
            {
                _perb.DeleteExpense_PaidReceiptOnly(Convert.ToInt32(id));

                Report = emp.FirstName + " " + emp.LastName + " has deleted the receipt of the payment record for " + ee.desc + " expense";
                AddNotification(Report);
                return RedirectToAction("ExpenseReceipt",new {id=ep.paid_exp_id});
            }
            catch(Exception c)
            { 
                   
            }
            return View("Index");
        }

        public static DateTime GetNistTime()
        {
            DateTime dateTime = DateTime.Now;
            try
            {
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create("http://nist.time.gov/actualtime.cgi?lzbc=siqm9b");
                request.Method = "GET";
                request.Accept = "text/html, application/xhtml+xml, */*";
                request.UserAgent = "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)";
                request.ContentType = "application/x-www-form-urlencoded";
                request.CachePolicy = new RequestCachePolicy(RequestCacheLevel.NoCacheNoStore);

                HttpWebResponse response = (HttpWebResponse)request.GetResponse();

WHSIC/WHSIC/Views/Expense_Paid/Create.cshtml
@model WHSIC.Model.Expense_PaidViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2>Add</h2>
@using (Html.BeginForm("Create","Expense_Paid",FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paid Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.exp_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3" >
                @Html.DropDownList("exp_id",(SelectList)ViewBag.m,"Select Expense Paid", new { @style = "width:262px;height:38px;" })
                @Html.ValidationMessageFor(model => model.exp_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.date_paid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_paid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount_paid, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.amount_paid, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.amount_paid, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            <table>
                <tr>
                    <td>
                        <label>Browse Receipt</label>
                    </td>

                    <td>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <div class="fileUpload btn btn-primary" style="background-color: #052963; color: #00C6D7">

                            @*<p>Click here to <span>Browse Receipt</span></p>*@
                            <input type="file" required="" onchange="readURL(this);" name="File" accept="application/doc, application/pdf" class="upload" />
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-3">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (ViewBag.feed != null)
{
    <script type="text/javascript">
            alert('@ViewBag.feed');
    </script>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WHSIC/WHSIC/Views/Expense_Paid/Delete.cshtml
@model WHSIC.Model.Expense_PaidViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paid Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpenseDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date_paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_paid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount_paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount_paid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WHSIC/WHSIC/Views/Expense_Paid/Details.cshtml
@model WHSIC.Model.Expense_PaidViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Expense_PaidViewModel</h4>
    <hr/>
    @Html.HiddenFor(model => model.paid_exp_id)
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpenseDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date_paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_paid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount_paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount_paid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.paid_exp_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WHSIC/WHSIC/Views/Expense_Paid/Edit.cshtml
@model WHSIC.Model.Expense_PaidViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2>Update</h2>


@using (Html.BeginForm("Edit","Expense_Paid",FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Paid Expense</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.paid_exp_id)
        <div class="form-group">
            @Html.LabelFor(model => model.exp_id, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.DropDownList("exp_id", (SelectList) ViewBag.m, "Select Expense Paid", new {@style = "width:262px;height:38px;"})
                @Html.ValidationMessageFor(model => model.exp_id, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_paid, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.date_paid, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.date_paid, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.Reference, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Reference, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount_paid, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-3">
                @Html.EditorFor(model => model.amount_paid, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.amount_paid, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <table>
                <tr>
                    <td>
                        <label>Browse Receipt</label>
                    </td>
                  
                    <td>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <div class="fileUpload btn btn-primary" style="background-color: #052963; color: #00C6D7">

                            @*<p>Click here to <span>Browse Receipt</span></p>*@
                            <input type="file" required="" onchange="readURL(this);" name="File" accept="application/doc, application/pdf" class="upload"/>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
@if (ViewBag.feed != null)
{
    <script type="text/javascript" >
        alert('@ViewBag.feed');
    </script>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WHSIC/WHSIC/Views/Expense_Paid/ExpenseReceipt.cshtml
@model IEnumerable<WHSIC.Model.PaidExpenseReceiptViewModel>
@{
    ViewBag.Title = "ExpenseReceipt";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<div class="well">
    <h2 class="text-center">Expense Receipt</h2>
    @if (ViewBag.count == 0)
    {
        <h3 style="color:#052963">The are no Receipts uploaded for this expense</h3>
    }
    <table class="table">
        <tr>
            <td>Date of upload</td>
            <td>Receipt</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                   click @Html.ActionLink("here","Showfile","Expense_Paid", new { id = item.Id }, new { target = "_blank" }) to view receipt
                </td>
            </tr>
        }
    </table>
    <div>
        @Html.ActionLink("Back to list","Index")
    </div>
</div>

WHSIC/WHSIC/Views/Expense_Paid/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<WHSIC.Model.Expense_PaidViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Treasure/_DashBoard.cshtml";
}

<h2>Paid Expenses</h2>

<div style="padding-bottom: 70px">
    @using (@Html.BeginForm())
    {
        <div class="col-md-3">
            <table>
                <tr>
                    <td>
                        @Html.TextBox("searchTerm", null, new { id = "txtSearch", @class = "form-control", placeholder = "Enter Expense Name", style = "width:300px" })
                    </td>
                    <td>
                        <input type="submit" value="Search" class="btn btn-primary" style="height: 37px" />
                    </td>
                </tr>
            </table>
        </div>
    }
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="well">

    <table class="table table-bordered table-hover table-striped">
        <tr>
            <th>
                Name of Expense
            </th>

            <th>
                Reference
            </th>

            <th>
                Date on
            </th>
            <th>
                Total Cost
            </th>
            <th>
                Amount paid
            </th>
            <th>
                Remaining Amount
            </th>
            <th>
                Receipts
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            WHSIC.Model.ExpenseViewModel exp = new WHSIC.Model.ExpenseViewModel();
            WHSIC.BusinessLogic.ExpenseBusiness eb = new WHSIC.BusinessLogic.ExpenseBusiness();
            exp = eb.GetAllExpenses().Find(x => x.exp_id == item.exp_id);
            decimal rem_amount = 0, totcost = exp.amount;
            rem_amount = exp.amount - item.amount_paid;

            TempData["rem"] = rem_amount.ToString("R00.00");
            TempData["Totcost"] = totcost.ToString("R00.00");
            TempData["Amount_paid"] = item.amount_paid.ToString("R00.00");

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpenseDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reference)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_paid)
                </td>
                <td>
                    @TempData["Totcost"]
                </td>
                <td>
                    @TempData["Amount_paid"]
                </td>
                <td>
                    @TempData["rem"]
                </td>
                <td>@Html.ActionLink("View Receipts", "ExpenseReceipt", new {id = item.paid_exp_id})</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = item.paid_exp_id}) |
                    @Html.ActionLink("Details", "Details", new {id = item.paid_exp_id}) |
                    @Html.ActionLink("Delete", "Delete", new {id = item.paid_exp_id})
                </td>
            </tr>
        }
        
    </table>
        <div class="text-center">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = Model.PageSize }))
        </div>
</div>

@section Scripts {
    <link href="~/Search_Jquery/AutoComplete/jquery-ui.css" rel="stylesheet" />
    <script src="~/Search_Jquery/AutoComplete/jquery-ui.js"></script>

    <script type="text/javascript">
        $(function() {
            $("#txtSearch").autocomplete({
                source: '@Url.Action("GetEmployees")'
            });
        });
    </script>
}